# -*- coding: utf-8 -*-
"""selenium_login_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaGZ8E5kOjTLk2JC-zbWsgilfDbjHh3o
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

# 1. Setup the Driver (Chrome)
driver = webdriver.Chrome()

# 2. Test Case: Verify Login Page Title
try:
    print("Test Started: Navigating to SwagLabs...")
    driver.get("https://www.saucedemo.com/")

    # Check if the title is right/correct
    actual_title = driver.title
    expected_title = "Swag Labs"

    if actual_title == expected_title:
        print(f"[PASS] Title matched: {actual_title}")
    else:
        print(f"[FAIL] Title Mismatch. Expected: {expected_title}, Got: {actual_title}")

    # 3. Test Case: Attempt Login
    driver.find_element(By.ID, "user-name").send_keys("standard_user")
    driver.find_element(By.ID, "password").send_keys("secret_sauce")
    driver.find_element(By.ID, "login-button").click()

    time.sleep(2) # Wait for load

    # 4. Validate Successful Login (Check URL)
    current_url = driver.current_url
    if "inventory.html" in current_url:
        print("[PASS] Login Successful - Redirected to Inventory")
    else:
        print("[FAIL] Login Failed")

except Exception as e:
    print(f"[ERROR] Test crashed: {e}")

finally:
    driver.quit()